name: Build Android Binary

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      # --- ИСПРАВЛЕНИЕ ЗДЕСЬ (Заменили на nttld/setup-ndk) ---
      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25c

      - name: Build
        run: |
          # Ищем папку с Makefile
          if [ -d "AndUEDumper/AndUEDumper" ]; then
            cd AndUEDumper/AndUEDumper
          elif [ -d "AndUEDumper" ]; then
             cd AndUEDumper
          fi
          
          echo "Текущая папка: $(pwd)"
          ls -la # Проверка файлов

          # Даем права скриптам
          chmod +x *.sh

          # Запускаем сборку
          make clean
          make

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AndUEDumper-Android
          path: |
            **/libs/**/*.so
            **/output/*
