name: Build Android Binary

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25c

      - name: Build
        run: |
          # Заходим в нужную папку
          if [ -d "AndUEDumper/AndUEDumper" ]; then
            cd AndUEDumper/AndUEDumper
          elif [ -d "AndUEDumper" ]; then
             cd AndUEDumper
          fi
          
          echo "Текущая папка: $(pwd)"

          # --- ИСПРАВЛЕНИЕ ЗДЕСЬ ---
          # Мы не используем make, потому что он ищет несуществующий файл.
          # Мы запускаем сборку напрямую через установленный NDK.
          # NDK сам найдет файл Android.mk в этой папке.
          
          ndk-build NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=Android.mk

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AndUEDumper-Android
          path: |
            **/libs/**/*.so
            **/output/*
